/**
 * Write a drafted case out as a TypeScript module.
 *
 * JSON would have been less work and would have been wrong. A case is read by a
 * human before it is ever played (D14), and reviewing prose is a thing people do
 * far better in a source file with comments in it than in a wall of quoted
 * strings. It also means a drafted case sits in the repository next to the
 * hand-written one, typed by the same schema, reviewed in the same diff.
 */
import type { CasePack } from '@tmv/core';

export function serialiseCase(pack: CasePack, brief: string, exportName: string): string {
  return `/**
 * ${pack.title}
 *
 * DRAFTED, NOT YET PUBLISHED. Generated by \`pnpm author\` from the brief:
 *   "${brief}"
 *
 * It passes the validator, which means the deduction is sound, the field
 * narrows, no clue gives the answer away and no player can solve it alone. It
 * does not mean the writing is any good, that the period is right, or that the
 * red herrings are fair. Read it before a room does (D14).
 *
 * Review checklist:
 *   - Does act 1 make you suspect the wrong person, and for a decent reason?
 *   - Does every clue that rules someone out say WHY, checkably?
 *   - Is there a moment in act 3 where it turns? Would you feel it?
 *   - Do the five suspects sound like five different people when read aloud?
 *   - Is anything in a knowledge sheet the solution in disguise?
 */
import type { CasePack } from '../case/types.js';
import { DECO_1920S_CHARACTERS } from '../cast/deco-1920s.js';

export const ${exportName}: CasePack = ${literal(pack, 0, { charactersToken: 'DECO_1920S_CHARACTERS' })};
`;
}

interface Opts {
  charactersToken?: string;
}

function literal(value: unknown, depth: number, opts: Opts, key?: string): string {
  const pad = '  '.repeat(depth + 1);
  const closePad = '  '.repeat(depth);

  if (key === 'characters' && opts.charactersToken) return opts.charactersToken;
  if (value === null || value === undefined) return 'undefined';
  if (typeof value === 'string') return quote(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((v) => `${pad}${literal(v, depth + 1, opts)}`);
    return `[\n${items.join(',\n')},\n${closePad}]`;
  }

  const entries = Object.entries(value as Record<string, unknown>).filter(
    ([, v]) => v !== undefined,
  );
  if (entries.length === 0) return '{}';
  const body = entries.map(([k, v]) => `${pad}${safeKey(k)}: ${literal(v, depth + 1, opts, k)}`);
  return `{\n${body.join(',\n')},\n${closePad}}`;
}

function safeKey(k: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : quote(k);
}

/**
 * Single quotes to match the house style, and the case prose is full of
 * apostrophes and curly quotes, so escape rather than switch quoting.
 */
function quote(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
}
